/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package javaapplication5;
import javax.swing.*;
import java.awt.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
/*
 *
 * @author alana
 */
public class Login extends javax.swing.JFrame {

    /** Creates new form Login */
    public Login() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(558, 360));
        setMaximumSize(new java.awt.Dimension(558, 360));
        setMinimumSize(new java.awt.Dimension(558, 360));
        setPreferredSize(new java.awt.Dimension(558, 360));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("SamsungOneUI Light Condensed", 1, 12)); // NOI18N
        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 70, 20));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 100, -1));
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 100, -1));

        jLabel5.setFont(new java.awt.Font("SamsungOneUI Light Condensed", 1, 14)); // NOI18N
        jLabel5.setText("Password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("SamsungOneUI Light Condensed", 1, 14)); // NOI18N
        jLabel4.setText("Username");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, 10));

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(79, 219, 56));
        jLabel7.setText("Care");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, 30));

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(56, 161, 219));
        jLabel6.setText("Life");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 40, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication5/images/Fixed New Logo.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, -40, 140, 210));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication5/images/background gray 2.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 190, 380));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication5/images/background login blue.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 570, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
        azure db = new azure();
        db.connect();
        String Username = jTextField1.getText();
	String Password = jPasswordField1.getText();
        String accessLevel = null;
        try
        {
            
            accessLevel = db.authorize(Integer.parseInt(Username), Password);
        }
        catch (Exception e){}
        
        System.out.println(Integer.parseInt(Username));
        System.out.println(Password);
        System.out.println(accessLevel);
        
        //accessLevel = "Doctor";
        
        if(accessLevel!= null && accessLevel.contains("Doctor"))
        {
            try {
                System.out.println("In Doctor");
                JOptionPane.showMessageDialog(null, "Login Successful");
                this.dispose();
                Doctor doctor = new Doctor();
                doctor.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        else if(accessLevel!= null && accessLevel.contains("Nurse"))
        {
            try {
                System.out.println("In nurse");
                JOptionPane.showMessageDialog(null, "Login Successful");
                this.dispose();
                Nurse nurse = new Nurse();
                nurse.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        else if(accessLevel!= null && accessLevel.contains("Registration"))
        {
            System.out.println("In reg");
            JOptionPane.showMessageDialog(null, "Login Successful");
             this.dispose();
            PatientSearch patient = new PatientSearch();
            patient.setVisible(true);
            System.out.println("In reg");
        }

        else if(accessLevel!= null && accessLevel.contains("Billing"))
        {
            System.out.println("In bill");
            JOptionPane.showMessageDialog(null, "Login Successful");
                 this.dispose();
            Billing billingsearch = new Billing();
            billingsearch.setVisible(true);
        }

        else
        {
            JOptionPane.showMessageDialog(null, "Username or Password mismatch ");
        }

        db.close();
        
        
        /*
        if (Username.equals("billing") && Password.equals("bills"))
        {
		JOptionPane.showMessageDialog(null, "Login Successful");
                 this.dispose();
                BillingSearch billingsearch = new BillingSearch();
                billingsearch.setVisible(true);
        }
        else if (Username.equals("nurse") && Password.equals("helps"))
                {
                    JOptionPane.showMessageDialog(null, "Login Successful");
                 this.dispose();
                Nurse nurse = new Nurse();
                nurse.setVisible(true);
                }
        else if (Username.equals("doctor") && Password.equals("diagnose"))
                {
                    JOptionPane.showMessageDialog(null, "Login Successful");
                 this.dispose();
                Doctor doctor = new Doctor();
                doctor.setVisible(true);
                }
        else if (Username.equals("patient") && Password.equals("sickness"))
                {
                    JOptionPane.showMessageDialog(null, "Login Successful");
                 this.dispose();
                Patient patient = new Patient();
                patient.setVisible(true);
                }
	else
		JOptionPane.showMessageDialog(null, "Username or Password mismatch ");
        */

        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
