/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication5;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultListModel;

/**
 *
 * @author alana
 */
public class ViewPatient extends javax.swing.JFrame {

    static azure db = new azure();
    static int count;
    /**
     * Creates new form AddPatient
     */
    public ViewPatient() throws SQLException {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); 
        count = setCount();
        jList1.setModel(setPatient());

        
    }

    /*
    public ViewPatient(int random)
    {
        
    }
*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 250));
        setMaximumSize(new java.awt.Dimension(460, 280));
        setMinimumSize(new java.awt.Dimension(460, 280));
        setPreferredSize(new java.awt.Dimension(460, 280));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "John Doe", "Jane Smith" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setToolTipText("");
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 410, 150));

        jLabel1.setText("Select a patient to view");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 20));

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 200, 60, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication5/images/background 5.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 460, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                this.dispose();
                String name = jList1.getSelectedValue();
                //String firstName
                String[] names = name.split("[^A-Za-z]+");
                String firstName = names[0];
                System.out.println(firstName);
                String lastName = names[1];
                System.out.println(lastName);

                db.connect();
                ResultSet patientInfo = db.getPatientByName(firstName, lastName);
                try
                {
                    System.out.println("In here");
                    Patient patient = new Patient(patientInfo);
                    patient.setVisible(true);
                }
                catch (Exception e)
                {
                }
                db.close();
                
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() 
            {
                try
                {
                    new ViewPatient().setVisible(true);
                }
                catch(Exception e)
                {
                    
                }
            }
        });
    }

    public DefaultListModel setPatient() throws SQLException
    {
        db.connect();
        DefaultListModel listModel = new DefaultListModel();

        ResultSet list = db.getPatientList();
        //list.next();
        System.out.println("here");
        System.out.println(count);
        do
        {
            String name = (list.getString(2).replaceAll("\\s", "") + " " + list.getString(3).replaceAll("\\s", ""));
            System.out.println(name);
            //System.out.println("boop");
            listModel.addElement(name);
            
            //listModel.addElement();
        }while(list.next());
        System.out.println(listModel.toString());

        //jList1.setModel(listModel);
        

        //System.out.println(jList1.get);
        

        /*
        jList1.setModel(new javax.swing.AbstractListModel<String>() 
        {
            String[] strings = { "John Doe", "Jane Bismark" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
*/
        
        db.close();
        return listModel;
    }

    public static int setCount()
    {
        db.connect();
        count = db.getPatientCount();
        db.close();
        return count;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
